version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/uuid-generator

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: "Running tests"
          command: yarn test

      - run:
          name: "Generate .env file"
          command: "./scripts/generateEnvFile.sh"

      - run:
          name: "Building extension"
          command: yarn build:prod

      - store_artifacts:
          path: build
          destination: ext

      - persist_to_workspace:
          root: ~/uuid-generator/build
          paths:
            - uuid_generator.zip

  publish:
    docker:
      - image: cibuilds/chrome-extension:latest

    steps:
      - attach_workspace:
          at: ~/uuid-generator/build

      - run:
          name: "Publishing to the Google Chrome Store"
          command: publish ~/uuid-generator/build/uuid_generator.zip

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/