name: UUID Chrome Extension build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
      - run: npm install
      - run: npm test
  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
        env:
          BROWSER: none
  pack:
    runs-on: ubuntu-latest
    needs:
      - build
      - e2e
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
      - run: npm install
      - run: npm run-script build
        env:
          GENERATE_SOURCEMAP: false
          INLINE_RUNTIME_CHUNK: false
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r main.zip build
